name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Check current directory
      run: pwd

    - name: List files
      run: ls -la

    - name: Generate configure script
      run: autoreconf -i

    - name: Run configure
      run: ./configure

    - name: Build project
      run: make